In [1]:
# zaimportowanie modulu 'geometria' i skrocenie nazwy na 'geo'
import geometria as geo

In [2]:
geo.pole_prostokata(5,10)

50

In [3]:
# instalacja numpy [powinna być domyślnie zainstalowana]
# (1) uruchomić Anaconda Promp [jako admin]
# (2) wpisać komendę: pip install numpy

In [4]:
# import biblioteki numpy
import numpy as np
# po wpisaniu 'np.' mozna nacisnac 'tab',
# aby zobaczyc liste opcji do wybrania

In [5]:
# ndarray [lista / tablica wielowymiarowa]

In [6]:
# np.array()
# np.arange()

In [7]:
# przykładowa, jednowymiarowa macierz

a = np.array([1,2,3,7,8,9])

In [8]:
a

array([1, 2, 3, 7, 8, 9])

In [9]:
b = np.arange(4)

In [10]:
b

array([0, 1, 2, 3])

In [11]:
c = np.arange(2,10,2)

In [12]:
c

array([2, 4, 6, 8])

In [13]:
e = np.array([[1,2,3],[4,5,6]])

In [14]:
e

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
f = np.zeros((2,3))

In [16]:
f

array([[0., 0., 0.],
       [0., 0., 0.]])

In [17]:
g = np.ones([2,3])

In [18]:
g

array([[1., 1., 1.],
       [1., 1., 1.]])

In [19]:
np.random.random((2,3))

array([[0.27632199, 0.7490417 , 0.50123652],
       [0.65703699, 0.60130011, 0.1973396 ]])

In [20]:
a = np.array([1,2,3])
b = np.array([4,5,7])

In [21]:
x = a+b

In [22]:
x

array([ 5,  7, 10])

In [23]:
x = a-b

In [24]:
x

array([-3, -3, -4])

In [25]:
x = a*b

In [26]:
x

array([ 4, 10, 21])

In [27]:
x = a/b

In [28]:
x

array([0.25      , 0.4       , 0.42857143])

In [29]:
x = a%b

In [30]:
x

array([1, 2, 3], dtype=int32)

In [31]:
x = a**2

In [32]:
x

array([1, 4, 9], dtype=int32)

In [33]:
a = np.array([[1,2,3],[7,8,9]])
b = np.array([[4,5,7],[1,4,5]])

In [34]:
y = a*b

In [35]:
y

array([[ 4, 10, 21],
       [ 7, 32, 45]])

In [36]:
y.shape

(2, 3)

In [37]:
y.T

array([[ 4,  7],
       [10, 32],
       [21, 45]])

In [38]:
y>30

array([[False, False, False],
       [False,  True,  True]])

In [39]:
y[2:]

array([], shape=(0, 3), dtype=int32)

In [40]:
a = np.array([1,2,3,7,8,9])

In [41]:
a[2:]

array([3, 7, 8, 9])

In [42]:
print(a[2]+a[4])

11


In [43]:
a[1:5]

array([2, 3, 7, 8])